# Generated by Django 4.2.1 on 2023-11-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record_payment",
            name="bills",
        ),
        migrations.RemoveField(
            model_name="record_payment",
            name="bills_item",
        ),
        migrations.AddField(
            model_name="bills",
            name="amount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bills.record_payment",
            ),
        ),
    ]
