# Generated by Django 4.2.1 on 2023-11-18 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record_Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Bank_payment", "Bank payment"),
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("Credit_card", "Credit_card"),
                            ("PayPal", "PayPal"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("amount", models.CharField(blank=True, max_length=200, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_account",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "bills",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bills.bills",
                    ),
                ),
                (
                    "bills_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bills.bills_item",
                    ),
                ),
            ],
        ),
    ]
