# Generated by Django 4.2.1 on 2023-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0002_remove_bills_expence_vendor_address1_vendor_address2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills_item",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
