# Generated by Django 4.2.1 on 2023-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_rename_amout_item_amount_remove_customer_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pos_so_no",
            field=models.TextField(blank=True, null=True),
        ),
    ]
