# Generated by Django 4.2.1 on 2023-11-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0004_customer_account_number_customer_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=200)),
                ("tax_rate", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("tax_num", models.BooleanField(default=False)),
                ("show_tax_number_on_invoices", models.BooleanField(default=False)),
                ("is_this_tax_recoverable", models.BooleanField(default=False)),
                ("is_this_a_compound_tax", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Product_Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.TextField(blank=True, null=True)),
                ("buy_this", models.BooleanField(default=False)),
                ("sell_this", models.BooleanField(default=False)),
                (
                    "income_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "expense_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sales_tax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice.tax",
                    ),
                ),
            ],
        ),
    ]
