# Generated by Django 4.2.1 on 2023-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0005_tax_alter_invoice_invoice_number_product_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_service",
            name="price",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
