# Generated by Django 4.2.1 on 2023-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_profile_id_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="File",
            field=models.FileField(blank=True, null=True, upload_to="static/file"),
        ),
    ]
