# Generated by Django 4.2.1 on 2023-10-06 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_file_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="File",
            new_name="file",
        ),
    ]
